import { NextResponse } from "next/server";
import { updateStore } from "@/lib/store";

export async function POST(
  request: Request,
  { params }: { params: Promise<{ classSectionId: string; subjectId: string }> }
) {
  const { classSectionId, subjectId } = await params;
  const body = await request.json(); // May contain action, chapterId, lessonId, format, etc.

  // Simulate AI generation delay
  await new Promise((resolve) => setTimeout(resolve, 1500));

  if (body.action === "preview") {
    // Return mock questions based on format
    const format = body.format || "Worksheet";
    const questions = [];
    
    if (format === "Objective") {
       questions.push("What is the primary function of the mitochondria?\n A) Energy production\n B) Protein synthesis\n C) Cell division\n D) Waste removal");
       questions.push("Which of the following is an example of a noble gas?\n A) Oxygen\n B) Nitrogen\n C) Helium\n D) Hydrogen");
       questions.push("What is the formula for calculating velocity?\n A) d/t\n B) m*a\n C) 1/2*m*v^2\n D) m*g*h");
       questions.push("In what year did World War II end?\n A) 1940\n B) 1945\n C) 1950\n D) 1939");
       questions.push("What is the capital of Japan?\n A) Beijing\n B) Seoul\n C) Tokyo\n D) Bangkok");
    } else {
       questions.push("Explain the process of photosynthesis in your own words. Be sure to mention the inputs and outputs.");
       questions.push("Compare and contrast the causes of the American Revolution with the French Revolution.");
       questions.push("Describe the structural differences between plant and animal cells.");
       questions.push("Solve the following mathematical equation and show all your steps: 3x^2 - 12x + 9 = 0.");
       questions.push("Write a short paragraph analyzing the main themes present in 'To Kill a Mockingbird'.");
    }

    return NextResponse.json({ questions }, { status: 200 });
  }

  // Handle actual submission (action === "submit" or default)
  const newAssignment = {
    id: `assign_ai_${Date.now()}`,
    classSectionId,
    subjectId,
    title: body.title || "AI Generated Practice Set",
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10), // +7 days
    description: body.description || "This assignment was generated by AI tailored to your selected criteria.",
    type: "AI Generated" as const,
    format: body.format || "Worksheet",
  };

  updateStore("assignments", (prev) => [...prev, newAssignment]);
  return NextResponse.json(newAssignment, { status: 201 });
}
